### ISSUE TITLE
quickstart postgres not working

### ISSUE THREAD

**Issue by howard-oc** [opencredo/flink-kratix-promise#13]
After the quickstart the promise failed running 
```bash
https://docs.kratix.io/main/quick-start#2-provide-postgres-as-a-service-via-a-kratix-promise
```

5m59s (x4 over 6m38s)   Normal    Created                Pod/configure-pipeline-postgresql-f6c6f-27n2l   Created container psql-promise-pipeline
99s (x25 over 6m36s)    Warning   BackOff                Pod/configure-pipeline-postgresql-f6c6f-27n2l   Back-off restarting failed container psql-promise-pipeline in pod configure-pipeline-postgresql-f6c6f-27n2l_kratix-platform-system(************************************)
44s                     Normal    SuccessfulDelete       Job/configure-pipeline-postgresql-f6c6f         Deleted pod: configure-pipeline-postgresql-f6c6f-27n2l
44s                     Warning   BackoffLimitExceeded   Job/configure-pipeline-postgresql-f6c6f         Job has reached the specified backoff limit

**Comment by burythehammer** [comment]
This issue is

**Comment by burythehammer** [comment]
not connected to our repo - closing.
