### ISSUE TITLE
Explore using KinD

### ISSUE THREAD

**Issue by howard-oc** [opencredo/flink-kratix-promise#40]
should we explore using KinD as well, as Syntasso themselves seem to indicate using it in their documentation? We should probably ask them whether using minikube is okay. I imagine their response will be the same as the Rust/Shell discussion but worth keeping in mind.

_Originally posted by @burythehammer in https://github.com/opencredo/promise-flink/pull/36#discussion_r1578043286_

**Comment by burythehammer** [comment]
We have explored this now and added some extra documentation as required. It seems to work okay!
