### ISSUE TITLE
promise/resource container image not available

### ISSUE THREAD

**Issue by kirederik** [opencredo/flink-kratix-promise#51]
hello,

we are looking into including this promise to the Kratix Marketplace (https://docs.kratix.io/marketplace) but it looks like the pipeline images are not published? I tried to install and use it locally, and found a couple of issues:

* `imagePullPolicy` is set to `Never`, so it requires the image to be on the node cache
* I remove the pull policy, but then I discovered the image is not yet published 😆

Would be great to get those two bits fixed so we can make it available on the Marketplace!

Thanks

**Comment by burythehammer** [comment]
I suspect this might be because you need to build the pipeline image locally first, though we haven't specified that in the README. Let me investigate this further and put any instructions as needed.

**Comment by kirederik** [comment]
Yeah, that fixes it. I was wondering if its worth pushing the image to dockerhub, so users don't have to go through those steps though?

**Comment by burythehammer** [comment]
It's possible, but also makes it harder for them to modify the workflow as needed. I think we'll have a chat tomorrow and work out what we want to do. This should fix this issue in the short term, though.

**Comment by burythehammer** [comment]
See also this PR which fixes things more substantially. We have uploaded an image to GHCR which will get pulled into the cluster. obviously you can still build your own workflow images locally too for debugging and development purposes.
